import "./globals.css";
import Nav from "./componentes/nav";
import Footer from "./componentes/footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/*<script src="https://cdn.jsdelivr.net/npm/eruda"></script>
    <script>eruda.init();</script>*/}
      </head>
      <body className="w-full flex flex-col h-full text-center bg-linear-to-r from-blue-900 to-blue-700  text-white">
        <Nav />
        <div className="flex-1 w-full h-full pt-8 items-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
