import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
	<head>
		<script src="https://cdn.jsdelivr.net/npm/eruda"></script>
<script>eruda.init();</script>
	</head>	  
      <body
      >
        {children}
      </body>
    </html>
  );
}
