import "./globals.css";
import Nav from "./componentes/nav";
import Footer from "./componentes/footer";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        {/*<script src="https://cdn.jsdelivr.net/npm/eruda"></script>
        <script>eruda.init();</script>*/}
      </head>
      <body className="min-h-screen w-full flex flex-col text-center bg-linear-to-r from-blue-900 to-blue-700 text-white">
        <Nav />
        <div className="flex-1 w-full pt-8 items-center">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
